spring:
#  profiles:
#    active: local
  application:
    name: transacao-service
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PWD}@${MONGO_HOST}/${MONGO_DB}?authSource=admin

server:
  port: ${PORT:0}

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}/eureka/
  instance:
    instance-id: ${spring.application.name}:${eureka.application.instance-id:${random.value}}
    hostname: ${RENDER_EXTERNAL_HOSTNAME}
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443
    prefer-ip-address: false
    status-page-url: ${RENDER_EXTERNAL_URL}/actuator/info
    health-check-url: ${RENDER_EXTERNAL_URL}/actuator/health